apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-golang-postgres
  labels:
    name: app-golang-postgres
spec:
  selector:
    matchLabels:
      app: app-golang-postgres
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: app-golang-postgres
    spec:
      containers:
        - image: postgres:alpine
          name: app-golang-postgres
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: app-golang-postgres-user
                  name: app-golang-secret
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: app-golang-postgres-password
                  name: app-golang-secret
            - name: POSTGRES_DB
              value: todolist
          ports:
            - containerPort: 5432
          livenessProbe:
            tcpSocket:
              port: 5432
      volumes:
        - name: app-golang-postgres-data
          emptyDir: {}
