apiVersion: v1
metadata:
  name: app-golang-todo
  labels:
    app: app-golang-todo
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: app-golang-todo
  type: NodePort
kind: Service