// Code generated by protoc-gen-go. DO NOT EDIT.
// source: taskservice.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Task struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TaskName             string   `protobuf:"bytes,2,opt,name=taskName,proto3" json:"taskName,omitempty"`
	Completed            bool     `protobuf:"varint,3,opt,name=completed,proto3" json:"completed,omitempty"`
	UserId               int64    `protobuf:"varint,4,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Task) Reset()         { *m = Task{} }
func (m *Task) String() string { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()    {}
func (*Task) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f9f4b593773f8c1, []int{0}
}

func (m *Task) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Task.Unmarshal(m, b)
}
func (m *Task) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Task.Marshal(b, m, deterministic)
}
func (m *Task) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Task.Merge(m, src)
}
func (m *Task) XXX_Size() int {
	return xxx_messageInfo_Task.Size(m)
}
func (m *Task) XXX_DiscardUnknown() {
	xxx_messageInfo_Task.DiscardUnknown(m)
}

var xxx_messageInfo_Task proto.InternalMessageInfo

func (m *Task) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Task) GetTaskName() string {
	if m != nil {
		return m.TaskName
	}
	return ""
}

func (m *Task) GetCompleted() bool {
	if m != nil {
		return m.Completed
	}
	return false
}

func (m *Task) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type GetAllTasksRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllTasksRequest) Reset()         { *m = GetAllTasksRequest{} }
func (m *GetAllTasksRequest) String() string { return proto.CompactTextString(m) }
func (*GetAllTasksRequest) ProtoMessage()    {}
func (*GetAllTasksRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f9f4b593773f8c1, []int{1}
}

func (m *GetAllTasksRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllTasksRequest.Unmarshal(m, b)
}
func (m *GetAllTasksRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllTasksRequest.Marshal(b, m, deterministic)
}
func (m *GetAllTasksRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllTasksRequest.Merge(m, src)
}
func (m *GetAllTasksRequest) XXX_Size() int {
	return xxx_messageInfo_GetAllTasksRequest.Size(m)
}
func (m *GetAllTasksRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllTasksRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllTasksRequest proto.InternalMessageInfo

type GetAllTasksResponse struct {
	Tasks                []*Task  `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllTasksResponse) Reset()         { *m = GetAllTasksResponse{} }
func (m *GetAllTasksResponse) String() string { return proto.CompactTextString(m) }
func (*GetAllTasksResponse) ProtoMessage()    {}
func (*GetAllTasksResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f9f4b593773f8c1, []int{2}
}

func (m *GetAllTasksResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllTasksResponse.Unmarshal(m, b)
}
func (m *GetAllTasksResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllTasksResponse.Marshal(b, m, deterministic)
}
func (m *GetAllTasksResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllTasksResponse.Merge(m, src)
}
func (m *GetAllTasksResponse) XXX_Size() int {
	return xxx_messageInfo_GetAllTasksResponse.Size(m)
}
func (m *GetAllTasksResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllTasksResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllTasksResponse proto.InternalMessageInfo

func (m *GetAllTasksResponse) GetTasks() []*Task {
	if m != nil {
		return m.Tasks
	}
	return nil
}

type GetTaskByIdRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTaskByIdRequest) Reset()         { *m = GetTaskByIdRequest{} }
func (m *GetTaskByIdRequest) String() string { return proto.CompactTextString(m) }
func (*GetTaskByIdRequest) ProtoMessage()    {}
func (*GetTaskByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f9f4b593773f8c1, []int{3}
}

func (m *GetTaskByIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTaskByIdRequest.Unmarshal(m, b)
}
func (m *GetTaskByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTaskByIdRequest.Marshal(b, m, deterministic)
}
func (m *GetTaskByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTaskByIdRequest.Merge(m, src)
}
func (m *GetTaskByIdRequest) XXX_Size() int {
	return xxx_messageInfo_GetTaskByIdRequest.Size(m)
}
func (m *GetTaskByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTaskByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTaskByIdRequest proto.InternalMessageInfo

func (m *GetTaskByIdRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetTaskByIdResponse struct {
	Task                 *Task    `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTaskByIdResponse) Reset()         { *m = GetTaskByIdResponse{} }
func (m *GetTaskByIdResponse) String() string { return proto.CompactTextString(m) }
func (*GetTaskByIdResponse) ProtoMessage()    {}
func (*GetTaskByIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f9f4b593773f8c1, []int{4}
}

func (m *GetTaskByIdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTaskByIdResponse.Unmarshal(m, b)
}
func (m *GetTaskByIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTaskByIdResponse.Marshal(b, m, deterministic)
}
func (m *GetTaskByIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTaskByIdResponse.Merge(m, src)
}
func (m *GetTaskByIdResponse) XXX_Size() int {
	return xxx_messageInfo_GetTaskByIdResponse.Size(m)
}
func (m *GetTaskByIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTaskByIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTaskByIdResponse proto.InternalMessageInfo

func (m *GetTaskByIdResponse) GetTask() *Task {
	if m != nil {
		return m.Task
	}
	return nil
}

type CreateTaskRequest struct {
	TaskName             string   `protobuf:"bytes,2,opt,name=taskName,proto3" json:"taskName,omitempty"`
	Completed            bool     `protobuf:"varint,3,opt,name=completed,proto3" json:"completed,omitempty"`
	UserId               int64    `protobuf:"varint,4,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTaskRequest) Reset()         { *m = CreateTaskRequest{} }
func (m *CreateTaskRequest) String() string { return proto.CompactTextString(m) }
func (*CreateTaskRequest) ProtoMessage()    {}
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f9f4b593773f8c1, []int{5}
}

func (m *CreateTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTaskRequest.Unmarshal(m, b)
}
func (m *CreateTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTaskRequest.Marshal(b, m, deterministic)
}
func (m *CreateTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTaskRequest.Merge(m, src)
}
func (m *CreateTaskRequest) XXX_Size() int {
	return xxx_messageInfo_CreateTaskRequest.Size(m)
}
func (m *CreateTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTaskRequest proto.InternalMessageInfo

func (m *CreateTaskRequest) GetTaskName() string {
	if m != nil {
		return m.TaskName
	}
	return ""
}

func (m *CreateTaskRequest) GetCompleted() bool {
	if m != nil {
		return m.Completed
	}
	return false
}

func (m *CreateTaskRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type CreateTaskResponse struct {
	Task                 *Task    `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTaskResponse) Reset()         { *m = CreateTaskResponse{} }
func (m *CreateTaskResponse) String() string { return proto.CompactTextString(m) }
func (*CreateTaskResponse) ProtoMessage()    {}
func (*CreateTaskResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f9f4b593773f8c1, []int{6}
}

func (m *CreateTaskResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTaskResponse.Unmarshal(m, b)
}
func (m *CreateTaskResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTaskResponse.Marshal(b, m, deterministic)
}
func (m *CreateTaskResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTaskResponse.Merge(m, src)
}
func (m *CreateTaskResponse) XXX_Size() int {
	return xxx_messageInfo_CreateTaskResponse.Size(m)
}
func (m *CreateTaskResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTaskResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTaskResponse proto.InternalMessageInfo

func (m *CreateTaskResponse) GetTask() *Task {
	if m != nil {
		return m.Task
	}
	return nil
}

type UpdateTaskRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TaskName             string   `protobuf:"bytes,2,opt,name=taskName,proto3" json:"taskName,omitempty"`
	Completed            bool     `protobuf:"varint,3,opt,name=completed,proto3" json:"completed,omitempty"`
	UserId               int64    `protobuf:"varint,4,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateTaskRequest) Reset()         { *m = UpdateTaskRequest{} }
func (m *UpdateTaskRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateTaskRequest) ProtoMessage()    {}
func (*UpdateTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f9f4b593773f8c1, []int{7}
}

func (m *UpdateTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTaskRequest.Unmarshal(m, b)
}
func (m *UpdateTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTaskRequest.Marshal(b, m, deterministic)
}
func (m *UpdateTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTaskRequest.Merge(m, src)
}
func (m *UpdateTaskRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateTaskRequest.Size(m)
}
func (m *UpdateTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTaskRequest proto.InternalMessageInfo

func (m *UpdateTaskRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateTaskRequest) GetTaskName() string {
	if m != nil {
		return m.TaskName
	}
	return ""
}

func (m *UpdateTaskRequest) GetCompleted() bool {
	if m != nil {
		return m.Completed
	}
	return false
}

func (m *UpdateTaskRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type UpdateTaskResponse struct {
	Task                 *Task    `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateTaskResponse) Reset()         { *m = UpdateTaskResponse{} }
func (m *UpdateTaskResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateTaskResponse) ProtoMessage()    {}
func (*UpdateTaskResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f9f4b593773f8c1, []int{8}
}

func (m *UpdateTaskResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTaskResponse.Unmarshal(m, b)
}
func (m *UpdateTaskResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTaskResponse.Marshal(b, m, deterministic)
}
func (m *UpdateTaskResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTaskResponse.Merge(m, src)
}
func (m *UpdateTaskResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateTaskResponse.Size(m)
}
func (m *UpdateTaskResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTaskResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTaskResponse proto.InternalMessageInfo

func (m *UpdateTaskResponse) GetTask() *Task {
	if m != nil {
		return m.Task
	}
	return nil
}

type DeleteTaskRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteTaskRequest) Reset()         { *m = DeleteTaskRequest{} }
func (m *DeleteTaskRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteTaskRequest) ProtoMessage()    {}
func (*DeleteTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f9f4b593773f8c1, []int{9}
}

func (m *DeleteTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteTaskRequest.Unmarshal(m, b)
}
func (m *DeleteTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteTaskRequest.Marshal(b, m, deterministic)
}
func (m *DeleteTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteTaskRequest.Merge(m, src)
}
func (m *DeleteTaskRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteTaskRequest.Size(m)
}
func (m *DeleteTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteTaskRequest proto.InternalMessageInfo

func (m *DeleteTaskRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteTaskResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteTaskResponse) Reset()         { *m = DeleteTaskResponse{} }
func (m *DeleteTaskResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteTaskResponse) ProtoMessage()    {}
func (*DeleteTaskResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f9f4b593773f8c1, []int{10}
}

func (m *DeleteTaskResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteTaskResponse.Unmarshal(m, b)
}
func (m *DeleteTaskResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteTaskResponse.Marshal(b, m, deterministic)
}
func (m *DeleteTaskResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteTaskResponse.Merge(m, src)
}
func (m *DeleteTaskResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteTaskResponse.Size(m)
}
func (m *DeleteTaskResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteTaskResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteTaskResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Task)(nil), "Task")
	proto.RegisterType((*GetAllTasksRequest)(nil), "GetAllTasksRequest")
	proto.RegisterType((*GetAllTasksResponse)(nil), "GetAllTasksResponse")
	proto.RegisterType((*GetTaskByIdRequest)(nil), "GetTaskByIdRequest")
	proto.RegisterType((*GetTaskByIdResponse)(nil), "GetTaskByIdResponse")
	proto.RegisterType((*CreateTaskRequest)(nil), "CreateTaskRequest")
	proto.RegisterType((*CreateTaskResponse)(nil), "CreateTaskResponse")
	proto.RegisterType((*UpdateTaskRequest)(nil), "UpdateTaskRequest")
	proto.RegisterType((*UpdateTaskResponse)(nil), "UpdateTaskResponse")
	proto.RegisterType((*DeleteTaskRequest)(nil), "DeleteTaskRequest")
	proto.RegisterType((*DeleteTaskResponse)(nil), "DeleteTaskResponse")
}

func init() { proto.RegisterFile("taskservice.proto", fileDescriptor_2f9f4b593773f8c1) }

var fileDescriptor_2f9f4b593773f8c1 = []byte{
	// 365 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x93, 0x4f, 0x4f, 0xb3, 0x40,
	0x10, 0xc6, 0x0b, 0xfd, 0x93, 0x76, 0x48, 0xde, 0x84, 0xa1, 0x79, 0x83, 0xe8, 0x81, 0xac, 0x1e,
	0x38, 0x2d, 0xa6, 0x1e, 0x4c, 0xbc, 0x59, 0x4d, 0x4c, 0x2f, 0x1e, 0x50, 0x2f, 0xde, 0x68, 0x99,
	0xc4, 0xa6, 0xad, 0x20, 0x4b, 0x4d, 0xfc, 0x56, 0x7e, 0x44, 0xb3, 0x0b, 0x16, 0x64, 0x8d, 0xbd,
	0xe8, 0x71, 0x9f, 0xce, 0xfc, 0x66, 0xfa, 0xcc, 0x03, 0xd8, 0x45, 0x2c, 0x56, 0x82, 0xf2, 0xd7,
	0xe5, 0x82, 0x78, 0x96, 0xa7, 0x45, 0xca, 0x9e, 0xa0, 0x77, 0x1f, 0x8b, 0x15, 0xfe, 0x03, 0x73,
	0x99, 0xb8, 0x86, 0x6f, 0x04, 0xdd, 0xc8, 0x5c, 0x26, 0xe8, 0xc1, 0x50, 0x16, 0xdf, 0xc6, 0x1b,
	0x72, 0x4d, 0xdf, 0x08, 0x46, 0xd1, 0xee, 0x8d, 0x47, 0x30, 0x5a, 0xa4, 0x9b, 0x6c, 0x4d, 0x05,
	0x25, 0x6e, 0xd7, 0x37, 0x82, 0x61, 0x54, 0x0b, 0xf8, 0x1f, 0x06, 0x5b, 0x41, 0xf9, 0x2c, 0x71,
	0x7b, 0x8a, 0x56, 0xbd, 0xd8, 0x18, 0xf0, 0x86, 0x8a, 0xcb, 0xf5, 0x5a, 0xce, 0x13, 0x11, 0xbd,
	0x6c, 0x49, 0x14, 0x6c, 0x02, 0xce, 0x17, 0x55, 0x64, 0xe9, 0xb3, 0x20, 0x3c, 0x84, 0xbe, 0xda,
	0xd5, 0x35, 0xfc, 0x6e, 0x60, 0x4d, 0xfa, 0x5c, 0xfe, 0x1c, 0x95, 0x1a, 0x3b, 0x51, 0x24, 0xa9,
	0x4c, 0xdf, 0x66, 0x49, 0x45, 0x6a, 0xff, 0x03, 0x76, 0xaa, 0xc8, 0x75, 0x55, 0x45, 0x3e, 0x80,
	0x9e, 0xa4, 0xa8, 0xc2, 0x1d, 0x58, 0x49, 0x8c, 0xc0, 0xbe, 0xca, 0x29, 0x2e, 0x48, 0x69, 0x15,
	0xf6, 0xf7, 0x8d, 0x08, 0x01, 0x9b, 0x63, 0xf6, 0xef, 0xb5, 0x05, 0xfb, 0x21, 0x4b, 0x5a, 0x7b,
	0xfd, 0xfd, 0xc1, 0x42, 0xc0, 0xe6, 0xd8, 0xfd, 0x7b, 0x1e, 0x83, 0x7d, 0x4d, 0x92, 0xf9, 0xc3,
	0x9e, 0x32, 0x06, 0xcd, 0xa2, 0x92, 0x3a, 0x79, 0x37, 0xc1, 0x92, 0xc2, 0x5d, 0x19, 0x4e, 0xbc,
	0x00, 0xab, 0x11, 0x0b, 0x74, 0xb8, 0x1e, 0x1d, 0x6f, 0xcc, 0xbf, 0x49, 0x0e, 0xeb, 0x54, 0xbd,
	0x9f, 0x87, 0x2f, 0x7b, 0x5b, 0x61, 0x29, 0x7b, 0xdb, 0xd9, 0x60, 0x1d, 0x3c, 0x07, 0xa8, 0x6f,
	0x83, 0xc8, 0xb5, 0x3c, 0x78, 0x0e, 0xd7, 0x8f, 0x57, 0x36, 0xd6, 0x66, 0x21, 0x72, 0xed, 0x60,
	0x9e, 0xc3, 0x75, 0x37, 0xcb, 0xc6, 0xda, 0x0f, 0x44, 0xae, 0x39, 0xe8, 0x39, 0x5c, 0x37, 0x8c,
	0x75, 0xa6, 0xd6, 0xe3, 0x88, 0x87, 0xd2, 0xf7, 0x30, 0x9b, 0xcf, 0x07, 0xea, 0x6b, 0x3e, 0xfb,
	0x08, 0x00, 0x00, 0xff, 0xff, 0xcd, 0xfb, 0xfd, 0x14, 0xe2, 0x03, 0x00, 0x00,
}
