apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-todolist-db-user
  labels:
    name: app-todolist-db-user
spec:
  selector:
    matchLabels:
      app: app-todolist-db-user
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: app-todolist-db-user
    spec:
      containers:
        - image: postgres:alpine
          name: app-todolist-db-user
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: app-todolist-postgres-user
                  name: app-golang-secret
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: app-todolist-postgres-password
                  name: app-golang-secret
            - name: POSTGRES_DB
              value: todolist
          ports:
            - containerPort: 5432
          livenessProbe:
            tcpSocket:
              port: 5432
      volumes:
        - name: app-todolist-db-user-data
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: app-todolist-db-user
  labels:
    app: app-todolist-db-user
spec:
  type: ClusterIP
  ports:
    - name: psql
      protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app: app-todolist-db-user
