apiVersion: v1
kind: Service
metadata:
  name: app-golang-postgres
  labels:
    app: app-golang-postgres
spec:
  type: NodePort
  ports:
    - name: psql
      protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app: app-golang-postgres
